### ISSUE TITLE
Add description to public landing page

### ISSUE THREAD

**Issue by colinpmillar** [ices-eg/wg_WGSFDGOV#1]
Populate the ICES landing page:

https://www.ices.dk/community/groups/Pages/WGSFDGOV.aspx

**Comment by jeffugo** [comment]
Hi @jensr 
I'm new and looking to make my first contribution to the open source community as a technical writer. I would love to help out with this issue.

**Comment by jensr** [comment]
@jeffugo 
Thank you very much for the offer, but at the moment, this task for set up of the basic information is aligned with an internal working group in the International Council for Exploration of the Seas. Later on, this board will be used to collect and prioritize issues related to spatial fisheries data, so you will be welcome to keep an eye on the boards if this is an area of interest :)

**Comment by christianvdorrien** [comment]
Dear all @ices-eg/wgsfdgov, below is a draft for the landing page. Please edit and comment as needed. Perhaps we can sign this off on Thursday. Cheers Christian

Spatial fisheries data are essential to understanding interactions between fisheries and the ecosystem. In order to describe fishing distribution – and considering its ecological footprint –VMS and logbook data provided by ICES member states are used and analysed by the Working Group on Spatial Fisheries Data (WGSFD). The Working Group on Spatial Fisheries Data Governance (WGSFDGOV was established at the beginning of 2020 to oversee the relevant processes for working with these data. WGSFDGOV will support the ICES Secretariat, the ICES Data Centre and WGSFD so that the following aims can be achieved:

-  All VMS and related logbook data held at ICES databases, as well as the corresponding data products will be secure in order not to compromise the protection of personal and commercial data of the fisheries from which the data originate.
-  The output of the respective ICES databases that form the basis of ICES advice will be reliable regarding data quality by conducting sufficient and effective quality checks.
- Review the spatial fisheries data calls and submissions to (a) rationalise the data needs; (b) provide easy and understandable guidance for those that have to answer the calls and submit data.

**Comment by neil-ices-dk** [comment]
_minor edits_ 

Spatial fisheries data are essential to understanding interactions between fisheries and the ecosystem. In order to describe fishing distribution – and considering its ecological footprint –Vessel Monitoring System (VMS) and logbook data provided by ICES member countries are used and analysed by the Working Group on Spatial Fisheries Data (WGSFD). The Working Group on Spatial Fisheries Data Governance (WGSFDGOV) was established at the beginning of 2020 to oversee the relevant processes for working with these data. WGSFDGOV will support the ICES Secretariat, the ICES Data Centre and WGSFD so that the following aims can be achieved:

- All VMS and related logbook data held at ICES databases, as well as the corresponding data products will be secure in order not to compromise the protection of personal and commercial data of the fisheries from which the data originate.

- The output of the respective ICES databases that form the basis of ICES advice will be reliable regarding data quality by conducting sufficient and effective quality checks.

- Review the spatial fisheries data calls and submissions to (a) rationalise the data needs; (b) provide easy and understandable guidance for those that have to answer the calls and submit data.

**Comment by christianvdorrien** [comment]
just sent it to Karolina
